import json

notebook_path = "notebooks/05_benchmark_5systems_pipeline.ipynb"
with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

new_source = [
    "# --- LOAD ALL MODELS ---\n",
    "print(\"Đang tải các mô hình...\")\n",
    "\n",
    "# Processor chung\n",
    "processor = Wav2Vec2Processor.from_pretrained(\"nguyenvulebinh/wav2vec2-base-vi-vlsp2020\")\n",
    "\n",
    "# S1: Pretrained Baseline\n",
    "model_pretrained = Wav2Vec2ForCTC.from_pretrained(\"nguyenvulebinh/wav2vec2-base-vi-vlsp2020\").to(device)\n",
    "model_pretrained.eval()\n",
    "\n",
    "# S2-S5: Custom Fine-tuned Model\n",
    "print(\"Đang tải Custom Wav2Vec2 model từ checkpoint...\")\n",
    "try:\n",
    "    import os, glob\n",
    "    checkpoint_path = WAV2VEC2_FINETUNED_PATH\n",
    "    \n",
    "    # Kiểm tra xem có phải thư mục HuggingFace (.bin hoặc .safetensors) không\n",
    "    is_hf_model = os.path.isdir(checkpoint_path) and (\n",
    "        os.path.exists(os.path.join(checkpoint_path, \"pytorch_model.bin\")) or \n",
    "        os.path.exists(os.path.join(checkpoint_path, \"model.safetensors\"))\n",
    "    )\n",
    "    \n",
    "    if is_hf_model:\n",
    "        print(f\"Loading weights directly from HuggingFace directory {checkpoint_path}...\")\n",
    "        model_finetuned = CustomWav2Vec2ForCTC.from_pretrained(checkpoint_path).to(device)\n",
    "    else:\n",
    "        # Khởi tạo cấu trúc mô hình custom từ pretrained base\n",
    "        model_finetuned = CustomWav2Vec2ForCTC.from_pretrained(\n",
    "            \"nguyenvulebinh/wav2vec2-base-vi-vlsp2020\",\n",
    "            pad_token_id=processor.tokenizer.pad_token_id,\n",
    "            vocab_size=len(processor.tokenizer)\n",
    "        )\n",
    "        \n",
    "        if os.path.isdir(checkpoint_path):\n",
    "            pt_files = glob.glob(os.path.join(checkpoint_path, \"*.pt*\"))\n",
    "            if pt_files:\n",
    "                checkpoint_path = pt_files[0]\n",
    "            else:\n",
    "                raise FileNotFoundError(f\"Không tìm thấy file .pt hay thư mục HF model hợp lệ trong {checkpoint_path}\")\n",
    "                \n",
    "        print(f\"Loading weights from PyTorch checkpoint {checkpoint_path}...\")\n",
    "        checkpoint = torch.load(checkpoint_path, map_location=device)\n",
    "        \n",
    "        # Hỗ trợ cả 2 định dạng checkpoint\n",
    "        if 'model_state' in checkpoint:\n",
    "            model_finetuned.load_state_dict(checkpoint['model_state'])\n",
    "        else:\n",
    "            model_finetuned.load_state_dict(checkpoint)\n",
    "            \n",
    "        model_finetuned = model_finetuned.to(device)\n",
    "    \n",
    "    print(\"✅ Tải Custom model thành công!\")\n",
    "except Exception as e:\n",
    "    print(f\"Không thể tải Custom model, fallback sang Wav2Vec2ForCTC base: {e}\")\n",
    "    model_finetuned = Wav2Vec2ForCTC.from_pretrained(\"nguyenvulebinh/wav2vec2-base-vi-vlsp2020\").to(device)\n",
    "\n",
    "model_finetuned.eval()\n",
    "\n",
    "# Pyctcdecode\n",
    "vocab_dict = processor.tokenizer.get_vocab()\n",
    "sorted_vocab = sorted((value, key) for (key, value) in vocab_dict.items())\n",
    "vocab_list = [key for (value, key) in sorted_vocab]\n",
    "vocab_list[vocab_dict[\"|\"]] = \" \"\n",
    "vocab_list = vocab_list[:model_pretrained.config.vocab_size]\n",
    "\n",
    "UNIGRAMS_PATH = \"/kaggle/input/datasets/hdtuznn/sppr-text/data/text/unigrams.txt\" # Upload file này lên Kaggle!\n",
    "unigrams_list = None\n",
    "if os.path.exists(UNIGRAMS_PATH):\n",
    "    with open(UNIGRAMS_PATH, \"r\", encoding=\"utf-8\") as f:\n",
    "        unigrams_list = [line.strip() for line in f if line.strip()]\n",
    "    print(f\"Đã nạp {len(unigrams_list):,} unigrams!\")\n",
    "else:\n",
    "    print(\"⚠ Không tìm thấy unigrams.txt, độ chính xác của KenLM có thể giảm sút!\")\n",
    "\n",
    "decoder_no_lm = build_ctcdecoder(labels=vocab_list, kenlm_model_path=None)\n",
    "decoder_kenlm = build_ctcdecoder(\n",
    "    labels=vocab_list, \n",
    "    kenlm_model_path=KENLM_PATH,\n",
    "    unigrams=unigrams_list,\n",
    "    alpha=0.5,\n",
    "    beta=1.0\n",
    ")\n",
    "\n",
    "# ViT5\n",
    "vit5_tokenizer = AutoTokenizer.from_pretrained(VIT5_PATH)\n",
    "vit5_model = AutoModelForSeq2SeqLM.from_pretrained(VIT5_PATH).to(device)\n",
    "vit5_model.eval()\n",
    "\n",
    "print(\"Hoàn tất tải toàn bộ hệ thống!\")\n"
]

for cell in nb['cells']:
    if cell['cell_type'] == 'code' and any('# --- LOAD ALL MODELS ---' in line for line in cell['source']):
        cell['source'] = new_source
        print("Updated LM cell!")
        break

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2, ensure_ascii=False)
